### ISSUE TITLE
problem with things re-evaluating field expressions whenever you access the field

### ISSUE THREAD

**Issue by AlexKnauth** [jarcane/heresy#16]
There is a problem with Things if the expressions in the fields involve side-effects (or expensive computations):
```racket
#lang s-exp heresy
(describe foo [a (print "Hi, I am the a field of foo")])
(print "line 3")
(foo 'a)
(print "line 5")
(foo 'a)
```
right now this produces the output:
```
line 3
Hi, I am the a field of foo
line 5
Hi, I am the a field of foo
```
when it should produce the output:
```
Hi, I am the a field of foo
line 3
line 5
```
By the way, I discovered this when I made [my-object](https://github.com/AlexKnauth/my-object), which was inspired by Things.  It solves this problem by having every "object" have a "λobject" that stores those lambdas, and having the actual object store a promise of the fields instead of the fields themselves, so that the object can be passed to those lambdas.  There is probably a simpler way to do it, but that's what I thought of first.  
By the way I first wanted to make that because I wanted to try out getting `(obj 'a 'b)` to mean get the `a` field of `obj` and then return the `b` field of that, and uses `(obj 'a 'b #:-> new-val)` to return an object like `obj` but with the `b` field of the `a` field functionally updated to `new-val`.  
Also by the way, it would probably be useful to have a macro for returning Things instead of defining them (analogous to my `object` macro), so if this macro was called `Thing`, then `(describe Name [field expr] ...)` would be equivalent to `(def Name (Thing [field expr] ...))`.

**Comment by jarcane** [comment]
I confess I didn't immediately cotton on to what the problem was in your sample first, but I think I see what you mean now. When assigning the result of an expression to a field, that field should only evaluate at the point of assignment, not over and over again. It's easy to miss in a language with no immutability and almost no side-effects, but it's a big bug in those rare times where you need something like that. And certainly it would be a performance hit if, say, a field was the result of a big list walk or something with `(for ...)`

Will merge.
