### ISSUE TITLE
Proposed feature: the math block.

### ISSUE THREAD

**Issue by jarcane** [jarcane/heresy#20]
Currently, the infix operator in Heresy is a pretty paltry thing which serves little real useful purpose. I have kept my eye open periodically for good solutions, and have had artyom's infix macro bookmarked to experiment with for sometime.

Today however, I've discovered a new option, and having been given permission from its creator, I'd like to try my hands at porting [Maya](https://gist.github.com/divs1210/b4fcbd48d7697dfd8850) to Heresy.

I quite like the syntax, it's rather reminiscent of Haskell's do blocks in some respects. It will take some supporting code to implement of course, in particular the `->` forward threading macro, and we'll need to decide how to handle the `:as` keyword with Heresy's syntax (as keywords aren't even yet defined for the language).

On the whole though, I think it's a doable and clever solution.

**Comment by AlexKnauth** [comment]
For the `->` threading macro, you could use rackjure's [`~>`](http://pkg-build.racket-lang.org/doc/rackjure/index.html#%28part._.Threading_macros%29).
For `:as`, I think just `as` would work and be consistent with the rest of heresy.  You probably would have to provide a way of defining macros that allows literals and multiple cases though, which you should probably do anyway.
Also you could look at a similar kind of thing I did with using syntax-parse splicing-syntax-classes to represent infix expressions with order of operations for the [m](http://pkg-build.racket-lang.org/doc/measures-with-dimensions/Operations__Types__and_Structs.html#%28form._%28%28lib._typed%2Fmeasures-with-dimensions..rkt%29._m%29%29) macro [here](https://github.com/AlexKnauth/measures-with-dimensions/blob/master/typed/measures-with-dimensions/untyped-operations.rkt#L23) if you wanted to control order of operations (I know Artyom's macro does this, but I didn't want to have to worry about whether it would parse things like (m 10 - 3 - 2) correctly).

**Comment by jarcane** [comment]
I had a weird idea about the literal keywords, and it comes by way of one of the things someone asked me in the HN thread announcing Heresy: why didn't I just use Racket keywords (ie. `#:foo`)?

The answer at the time was "I didn't think about it" and "Because it's not how BASIC's work."

But I had another "dumb idea" last night, that might solve our messy literal problem, and it involves Racket keywords. 

Now that we've got our own `#%app` macro, what if we extended it to allow a new kind of definition that resolves a name to a #:keyword? Macros and functions with literals could then just be written using #:keywords, with a `keyword` function being used to define the bare name. So I could do something like this, and it'd work:

```
(keyword "dave")
(def fn foo (#:dave bar) ...)

(foo dave ...) ; expands (foo #:dave ...)
```
The application of defined keywords would have to take place at an earlier phase, somewhere in the  apply or read levels; a simple syntax-id-rules for instance doesn't work, it happens later than the phase where Racket checks a function's arguments so you get an error. But if it could be pulled off at an earlier phase so that it splices in the keyword before Racket checks the arguments, then it would be largely transparent in use.

It means our defined keywords are still cluttering up the name space as before (really wish literals could be safely local defined :disappointed:), but it's cleaner at least, and crucially, would be a way to do it that would allow you to define new literal keywords in Heresy itself, instead of those being Racket-level special forms only.

**Comment by AlexKnauth** [comment]
On Jan 9, 2015, at 12:19 AM, John Berry <notifications@github.com> wrote:

> I had a weird idea about the literal keywords,
> 
This is confusing.  Do you mean literals (like `fn` in `(def fn …)`) or `#:keywords` (like `#:transparent` in `(struct foo () #:transparent)`) ?
> and it comes by way of one of the things someone asked me in the HN thread announcing Heresy: why didn't I just use Racket keywords (ie. #:foo)?
> 
> The answer at the time was "I didn't think about it" and "Because it's not how BASIC's work.”
> 
I think for some things `#:keywords` are much better, but for a lot of your uses of literals, I think they would look worse.
> But I had another "dumb idea" last night, that might solve our messy literal problem, and it involves Racket keywords.
> 
> Now that we've got our own #%app macro, what if we extended it to allow a new kind of definition that resolves a name to a #:keyword? Macros and functions with literals could then just be written using #:keywords, with a keyword function being used to define the bare name. So I could do something like this, and it'd work:
> 
> (keyword "dave")
> (def fn foo (#:dave bar) …)
But this already works in heresy:
```racket
#lang s-exp heresy
(def fn foo (#:dave bar) (+ bar 1))
(foo #:dave 5) ;=> 6
```
> (foo dave ...) ; expands (foo #:dave …)
Um, what?  Why not have them write `(foo #:dave …)` in the first place?  Otherwise in a function application they might get confused about
whether an identifier is a variable or a literal.  That’s part of the whole point of having `#:keywords` not be expressions.
> The application of defined keywords
> 
Keywords as in `#:keywords` are never defined.  They are used just like datum-literals, because they have no binding and when a keyword is 
used it is never expanded or checked for a binding, but if it is used within a macro (racket’s `#%app` here is such a macro), that macro can 
recognize keywords and expand differently based on whether a #:keyword is present or not.  So at the macro level, they are used just like your 
literals, except that they don’t have a binding.  This is good for some things and not as good (compared to literals) for others.  
> would have to take place at an earlier phase,
> 
No, they do not take place at an earlier phase than macro expansion.
> somewhere in the apply or read levels; a simple syntax-id-rules for instance doesn't work,
> 
If you want to have a macro use a #:keyword, a simple syntax-rules or syntax-id-rules will work.
> it happens later than the phase where Racket checks a function's arguments so you get an error. But if it could be pulled off at an earlier phase so that it splices in the keyword before Racket checks the arguments, then it would be largely transparent in use.
> 
> It means our defined keywords are still cluttering up the name space as before (really wish literals could be safely local defined ), but it's cleaner at least, and crucially, would be a way to do it that would allow you to define new literal keywords in Heresy itself, instead of those being Racket-level special forms only.
> 
By this do you mean #:keywords or literals?  
Neither would solve the problems we in https://github.com/jarcane/heresy/issues/6, because unless you do something where the macro
that’s using it does something special like rewriting (def id …) to (def/id …), they would still have to be hard-coded into the macro, and
they wouldn’t be able to be extended from other modules, whether they’re heresy modules or racket modules.  

What you can do is provide a form that let’s you define a macro from within heresy that uses literals or #:keywords.
For #:keywords, that’s already done, because something like this already works:
```racket
#lang s-exp heresy
(def macro foo (#:dave bar) (+ bar 1))
(foo #:dave 5) ;=> 6
```
But this really isn’t very useful unless you provide a way of defining macros that’s more like syntax-rules than define-syntax-rule.
And if you want to be able to define new literals (not #:keywords, because they don’t have to be) in Heresy itself, you could just provide something like this, which also solves both problems:
```racket
;; (define-syntax-rules macro-id [pat body] ...)
;; (define-syntax-rules macro-id #:literals (lit-id ...) [pat body] ...)
(define-syntax define-syntax-rules
  (syntax-rules ()
    [(define-syntax-rules macro-id #:literals (lit-id ...) [pat body] ...)
     (begin
       (define-syntax-parameter lit-id (lambda (stx) (raise-syntax-error #f (format "cannot be used outside of ~a" 'macro-id) stx)))
       ...
       (define-syntax macro-id
         (syntax-rules (lit-id ...) [pat body] ...)))]
    [(define-syntax-rules macro-id [pat body] ...)
     (define-syntax-rules macro-id #:literals () [pat body] ...)]))

(define-syntax-rules my-macro #:literals (lit-1 lit-2)
  [(my-macro lit-1 stuff ...) "you used lit-1!"]
  [(my-macro lit-2 stuff ...) "you used lit-2!"])

```

Or it might be that I’m completely misunderstanding your point.

**Comment by jarcane** [comment]
You might be, but the idea's pretty half baked, and you make some good arguments against it anyway. It was mainly something that struck me about the `:as` component of Maya, and wondering if we could get that same use but with a bare name, to save pain. But Clojure keywords work differently to Racket values, and if I'm following you correctly that's a pretty deeply rooted part of the language not easily changed anyway. 

To clarify though, what I mean by `literal keywords` is stuff like we have in Heresy: `fn`, `macro`, `with`, and so on.

By Racket keywords I mean indeed the Racket usage: `#:foo` and such.

What I thought was if we could define a way of making a reader macro that would exchange one for the other, so that say, `(def fn  name ...` is defined internally as `(def #:fn name ...)`, but `fn` has been defined with some other function like `(keyword fn)` or something to resolve to `#:fn` before the function is actually applied. But if I'm understanding what you've said here properly, that's one thing that just plain isn't possible with how Racket handles the #:keywords?

**Comment by AlexKnauth** [comment]
I think it would look better in heresy for it to be just `as` (a normal literal), although if I were doing this I would probably do something more like
```racket
(math #:with a + b as c
      c * 5)
```

What do you mean by "But Clojure keywords work differently to Racket values, and if I'm following you correctly that's a pretty deeply rooted part of the language not easily changed anyway." ?  

In my opinion, your use of `literal keywords` in a context where we are also talking about #:keywords (which can also be known as `keyword literals`) is confusing, but okay.

A reader macro?  That wouldn't make any sense.  But you could define `def` in such a way that it translated `(def fn name ...)` to `(def #:fn name ...)`, but that wouldn't make any sense because why not just forget the `#:fn` case and just translate `(def fn name ...)` to what it needs to be directly?  

Why would you need `(keyword fn)`?  If `fn` is already defined as a `lambda`-like macro, then all `def` needs to do is look at the identifier and see whether it matches the binding of `fn`.  If `fn` is not already defined, then you can just use `(define-syntax fn #f)`, and it doesn't have anything to do with any #:keywords.

What do you mean about something that isn't possible with how Racket handles #:keywords?  Racket doesn't handle #:keywords in any weird way, except that it doesn't allow them to be normal expressions, so that macros can use them to mean special things.

**Comment by jarcane** [comment]
In Clojure, keywords (ie. `:as`) are normal values, and they can be put just about anywhere. In Racket, there are very specific rules about when and where you can use keywords, and you will get errors if you use them anywhere else than it expects (mainly function/macro arguments and hash-tables).

My apologies about the confusing terminology. I'm jumping around languages a lot at the moment (expanding my skills in FP stuff because I might be needing to look for work sooner than expected), and what Racket calls a "keyword" is different from what BASIC or Haskell do.

To get back towards the original topic, I think you are largely correct, and furthermore, `as` is already a reserved syntax parameter anyway so not immediately relevant to the Maya syntax.

**Comment by jarcane** [comment]
As this has now been merged, I'm considering this issue closed. 

Thanks for the good work, and my sincerest apologies for my absence and poor handling of this.
